import { StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
    welcome: {
      flex: 1,
      backgroundColor: '#fcb456',
      alignItems: 'center',
      justifyContent: 'center',
    },
    welcomeTextMain: {
      fontSize: 50,
      color: 'white',
      fontWeight: 'bold',
    },
    welcomeTextSub: {
      fontSize: 25,
      color: 'white',
      fontWeight: 'bold',
      marginTop: 30,
    },
    content: {
      flex: 1,
      backgroundColor: '#f5f5f5',
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeContent: {
      flex: 1,
      backgroundColor: '#f5f5f5',
      padding: 20,
      marginBottom: -20,
    },
    feedbackContainer: {
      padding: 20,
      marginBottom: -20,
      flex: 1,
      backgroundColor: '#f5f5f5',
    },
    feedbackContainerFalse: {
      padding: 20,
      marginBottom: -20,
      flex: 1,
      backgroundColor: '#f5f5f5',
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabHeader: {
      fontSize: 20,
      marginBottom: 20,
      fontWeight: 'bold',
      color: 'gray',
    },
    detailBox: {
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 15,
      margin: 20,
      marginBottom: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
    },
    detailTitle: {
      color: 'gray',
      fontSize: 25,
      fontWeight: 'bold',
      marginBottom: 15,
    },
    detailTime: {
      color: 'gray',
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 30,
    },
    detailBody: {
      margin:-5,
      fontSize: 15,
      color: 'gray',
    },
    recentFeedbackFalse: {
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 10,
      marginBottom: 10,
      color: 'white',
      backgroundColor: '#a3a3a3',
      justifyContent: 'center',
      alignItems: 'center',
    },
    recentFeedbackFalseText: {
      fontSize: 20,
      margin: 7,
      fontWeight: 'bold',
      color: 'white',
    },
    FlatList: {
      flexGrow: 0,
      marginBottom: 10,
    },
    timerStopwatch: {
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 28,
      color: 'white',
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 19.8,
    },
    timerButtonText: {
      borderRadius: 10,
      padding: 5,
      borderColor: '#fcb456',
      color: '#fcb456',
      borderWidth: 1,
      fontSize: 20,
    },
    startResetText: {
      margin: 10,
      marginBottom: -5,
      marginTop: 20,
      borderRadius: 10,
    },
    recordStartButton: {
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 85,
      marginBottom: 20,
      color: 'white',
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
    },
    recordStartText: {
      fontSize: 30,
      color: '#fcb456',
      fontWeight: '500',
    },
    recordSelectText: {
      fontSize: 25,
      color: '#fcb456',
      fontWeight: '500',
    },
    recordSelectButton: {
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 34,
      marginBottom: 10,
      color: 'white',
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
    },
    testIMG: {
      width: 220,
      height: 300,
      borderRadius: 10,
      marginTop: -12,
      marginBottom:25,
    },
    wishTime: {
      // height:'32%',
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 28,
      color: 'white',
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
      flexShrink: 1,
      marginBottom:20,
    },
    wishTimeText: {
      fontSize: 20,
      color: '#fcb456',
      fontWeight: 'bold',
    },
    wishTimeTextInStopWatch: {
      fontSize: 21,
      marginTop: -15,
      marginBottom: 10,
      color: '#fcb456',
      fontWeight: 'bold',
    },
    CorrectionTipContainer: {
      margin: 15,
      padding: 20,
      flex: 1,
      width: '90%',
      borderRadius: 10,
      backgroundColor: 'white',
      alignItems: 'center',
    },
    correctionCautionTitle: {
      color: 'gray',
      fontSize: 27,
      fontWeight: 'bold',
    },
    correctionCautionSubTitle: {
      color: 'gray',
      fontSize: 15,
      fontWeight: 'bold',
      marginTop: -15,
    },
    correctionCautionContent: {
      color: 'gray',
      fontSize: 15,
    },
    correctionCautionImage: {
      width: 100,
      height: 150,
      borderRadius: 5,
      margin: 20,
    },
    uploadVideo: {
      width: '90%',
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 10,
      marginBottom: 15,
      color: 'white',
      backgroundColor: '#fcb456',
      justifyContent: 'center',
      alignItems: 'center',
    },
    homeUploadVideo: {
      width: '100%',
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 15,
      marginBottom: 15,
      color: 'white',
      backgroundColor: '#fc7d56',
      justifyContent: 'center',
      alignItems: 'center',
    },
    homeUploadVideo2: {
      width: '100%',
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 15,
      marginBottom: 15,
      color: 'white',
      backgroundColor: '#947469',
      justifyContent: 'center',
      alignItems: 'center',
    },
    uploadVideoText: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 18,
      margin: 5,
    },
    calendar: {
      borderBottomWidth: 1,
      borderBottomColor: '#e0e0e0',
    },
    calendarContent: {
      flex: 1,
      alignItems: 'center',
    },
    calendarContentNodata: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    calendarContentText: {
      fontSize: 16,
      color: 'gray',
    },
    CalendarContentBox: {
      backgroundColor: '#FFFFFF',
      width: '100%',
      padding: 10,
      borderRadius: 5,
      alignItems: 'center',
    },
    calendarContentTime: {
      width: '90%',
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 17,
      marginTop: 15,
      color: 'white',
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
    },
    calendarContentFeedback: {
      width: '90%',
      borderRadius: 10,
      borderColor: 'white',
      borderWidth: 1,
      padding: 17,
      marginTop: 15,
      color: 'white',
      backgroundColor: '#fcb456',
      justifyContent: 'center',
      alignItems: 'center',
    },
    calendarContentTimeText: {
      fontSize: 20,
      fontWeight: 'bold',
      color: 'gray',
    },
    calendarContentFeedbackText: {
      fontSize: 20,
      fontWeight: 'bold',
      color: 'white',
    },
    letter:{
      fontSize: 16,
      margin:-3,
      color: 'white',
    },
    startRecentContainer:{
      borderRadius: 10,
      borderColor: "white",
      borderWidth: 1,
      padding: 10,
      marginBottom: 10,
      color: "white",
      backgroundColor: "#fcb456",
      justifyContent:'center',
      alignItems:'center'
    },
    startRecentTitleText:{
        color: "white",
        fontSize: 15,
        marginBottom: 5,
    },
    startRecentTimeText:{
      color: "white",
      fontSize: 13,
    }
  });
  